<?php

use Spatie\LaravelSettings\Migrations\SettingsMigration;

return new class extends SettingsMigration
{
public function up(): void
{
        $this->migrator->add('translatable_verwalterservicelandingpage.hero_tagline_de', 'Professionell. Persönlich. Verlässlich.');
        $this->migrator->add('translatable_verwalterservicelandingpage.hero_tagline_en', 'Professional. Personal. Reliable.');
        $this->migrator->add('translatable_verwalterservicelandingpage.hero_headline_de', 'Unser Service für Verwalter: Wir arbeiten. Sie profitieren.');
        $this->migrator->add('translatable_verwalterservicelandingpage.hero_headline_en', 'Our Service for Managers: We work. You benefit.');
        $this->migrator->add('translatable_verwalterservicelandingpage.hero_email', 'verwalterservice@bereal-immobilien.at');
        $this->migrator->add('translatable_verwalterservicelandingpage.hero_phone', '+43 1 535 36 19');
        $this->migrator->add('translatable_verwalterservicelandingpage.hero_feature_1_de', 'Schnelle Unterstützung');
        $this->migrator->add('translatable_verwalterservicelandingpage.hero_feature_1_en', 'Fast Support');
        $this->migrator->add('translatable_verwalterservicelandingpage.hero_feature_2_de', 'Lückenlose Dokumentation');
        $this->migrator->add('translatable_verwalterservicelandingpage.hero_feature_2_en', 'Complete Documentation');
        $this->migrator->add('translatable_verwalterservicelandingpage.hero_feature_3_de', 'Flexible Einsatzzeiten');
        $this->migrator->add('translatable_verwalterservicelandingpage.hero_feature_3_en', 'Flexible Deployment Times');
        $this->migrator->add('translatable_verwalterservicelandingpage.section_1_tag_de', 'be serviced');
        $this->migrator->add('translatable_verwalterservicelandingpage.section_1_tag_en', 'be serviced');
        $this->migrator->add('translatable_verwalterservicelandingpage.section_1_headline_de', 'Professionelle Unterstützung für Ihre Hausverwaltung');
        $this->migrator->add('translatable_verwalterservicelandingpage.section_1_headline_en', 'Professional Support for Your Property Management');
        $this->migrator->add('translatable_verwalterservicelandingpage.section_1_text_de', 'Sie möchten sich auf Eigentümer, Strategie und Wachstum konzentrieren – ohne sich im Tagesgeschäft zu verlieren? Wir unterstützen kleine Hausverwaltungen dort, wo operative Aufgaben Zeit, Ressourcen und Nerven kosten. Mit klaren Prozessen, sauberer Dokumentation und einem Team, das weiß, worauf es ankommt. Wir übernehmen operative Leistungen rund um Ihre Immobilien und sorgen dafür, dass Abläufe strukturiert, transparent und effizient bleiben. Unsere Unterstützung umfasst unter anderem: Objektbuchhaltung, Mahnwesen & Inkasso, Objektbegehungen & Zustandskontrollen, Schadensdokumentation & Versicherungsabwicklung, Sanierungsbegleitung, Energieausweise.');
        $this->migrator->add('translatable_verwalterservicelandingpage.section_1_text_en', 'You want to focus on owners, strategy and growth – without getting lost in day-to-day operations? We support small property management companies where operational tasks cost time, resources and nerves. With clear processes, clean documentation and a team that knows what matters. We take over operational services for your properties and ensure that processes remain structured, transparent and efficient.');
        $this->migrator->add('translatable_verwalterservicelandingpage.section_1_feature_1_de', 'Objektbuchhaltung');
        $this->migrator->add('translatable_verwalterservicelandingpage.section_1_feature_1_en', 'Property Accounting');
        $this->migrator->add('translatable_verwalterservicelandingpage.section_1_feature_2_de', 'Mahnwesen & Inkasso');
        $this->migrator->add('translatable_verwalterservicelandingpage.section_1_feature_2_en', 'Dunning & Collection');
        $this->migrator->add('translatable_verwalterservicelandingpage.section_1_feature_3_de', 'Objektbegehungen');
        $this->migrator->add('translatable_verwalterservicelandingpage.section_1_feature_3_en', 'Property Inspections');
        $this->migrator->add('translatable_verwalterservicelandingpage.section_1_feature_4_de', 'Schadensdokumentation');
        $this->migrator->add('translatable_verwalterservicelandingpage.section_1_feature_4_en', 'Damage Documentation');
        $this->migrator->add('translatable_verwalterservicelandingpage.section_1_feature_5_de', 'Sanierungsbegleitung');
        $this->migrator->add('translatable_verwalterservicelandingpage.section_1_feature_5_en', 'Renovation Support');
        $this->migrator->add('translatable_verwalterservicelandingpage.section_1_feature_6_de', 'Energieausweise');
        $this->migrator->add('translatable_verwalterservicelandingpage.section_1_feature_6_en', 'Energy Certificates');
        $this->migrator->add('translatable_verwalterservicelandingpage.section_1_cta_de', 'Jetzt unverbindlich beraten lassen');
        $this->migrator->add('translatable_verwalterservicelandingpage.section_1_cta_en', 'Get advice now without obligation');
        $this->migrator->add('translatable_verwalterservicelandingpage.section_2_tag_de', 'be cared');
        $this->migrator->add('translatable_verwalterservicelandingpage.section_2_tag_en', 'be cared');
        $this->migrator->add('translatable_verwalterservicelandingpage.section_2_headline_de', '360°-Leistungen für Immobilienverwaltungen');
        $this->migrator->add('translatable_verwalterservicelandingpage.section_2_headline_en', '360° Services for Property Management');
        $this->migrator->add('translatable_verwalterservicelandingpage.section_2_text_de', 'Von der regelmäßigen Begehung bis zur professionellen Projektbegleitung: Wir bieten ein modulares Leistungspaket, das sich an Ihre Anforderungen anpasst.');
        $this->migrator->add('translatable_verwalterservicelandingpage.section_2_text_en', 'From regular inspections to professional project support: We offer a modular service package that adapts to your requirements.');
        $this->migrator->add('translatable_verwalterservicelandingpage.service_1_title_de', 'Objektbuchhaltung');
        $this->migrator->add('translatable_verwalterservicelandingpage.service_1_title_en', 'Property Accounting');
        $this->migrator->add('translatable_verwalterservicelandingpage.service_1_description_de', 'Sorgfältige und transparente Abwicklung sämtlicher buchhalterischer Agenden rund um Ihre Liegenschaften. Von der laufenden Verbuchung über Betriebskostenabrechnungen bis zur Eigentümerabrechnung – wir sorgen für strukturierte Prozesse, termingerechte Abschlüsse und vollständige Nachvollziehbarkeit aller Zahlen.');
        $this->migrator->add('translatable_verwalterservicelandingpage.service_1_description_en', 'Careful and transparent handling of all accounting matters for your properties. From ongoing bookkeeping to operating cost statements and owner accounting – we ensure structured processes, timely completion and full traceability of all figures.');
        $this->migrator->add('translatable_verwalterservicelandingpage.service_2_title_de', 'Mahnwesen & Inkasso');
        $this->migrator->add('translatable_verwalterservicelandingpage.service_2_title_en', 'Dunning & Collection');
        $this->migrator->add('translatable_verwalterservicelandingpage.service_2_description_de', 'Konsequentes, professionelles Forderungsmanagement mit Fingerspitzengefühl. Wir übernehmen Zahlungserinnerungen, Mahnläufe und – falls erforderlich – die Koordination mit Rechtsanwälten oder Inkassodienstleistern. Ziel ist eine rasche Liquiditätssicherung bei gleichzeitiger Wahrung eines sachlichen Umgangs.');
        $this->migrator->add('translatable_verwalterservicelandingpage.service_2_description_en', 'Consistent, professional claims management with sensitivity. We handle payment reminders, dunning procedures and – if necessary – coordination with lawyers or collection agencies. The goal is rapid liquidity assurance while maintaining professional conduct.');
        $this->migrator->add('translatable_verwalterservicelandingpage.service_3_title_de', 'Objektbegehungen & Zustandskontrollen');
        $this->migrator->add('translatable_verwalterservicelandingpage.service_3_title_en', 'Property Inspections & Condition Checks');
        $this->migrator->add('translatable_verwalterservicelandingpage.service_3_description_de', 'Regelmäßige Vor-Ort-Begehungen zur Sicherstellung des ordnungsgemäßen Objektzustands. Wir dokumentieren den baulichen und technischen Status mittels strukturierter Berichte und Fotodokumentation, identifizieren frühzeitig Handlungsbedarf und schaffen Transparenz für Eigentümer und Verwaltung.');
        $this->migrator->add('translatable_verwalterservicelandingpage.service_3_description_en', 'Regular on-site inspections to ensure proper property condition. We document structural and technical status through structured reports and photo documentation, identify action needs early and create transparency for owners and management.');
        $this->migrator->add('translatable_verwalterservicelandingpage.service_4_title_de', 'Schadensdokumentation & Versicherungsabwicklung');
        $this->migrator->add('translatable_verwalterservicelandingpage.service_4_title_en', 'Damage Documentation & Insurance Processing');
        $this->migrator->add('translatable_verwalterservicelandingpage.service_4_description_de', 'Professionelle Erfassung und Aufbereitung von Schadensfällen – von der Erstaufnahme bis zur vollständigen Abwicklung mit der Versicherung. Wir koordinieren Professionisten, überwachen Fristen und sorgen für eine lückenlose Dokumentation, damit Ansprüche effizient und korrekt abgewickelt werden.');
        $this->migrator->add('translatable_verwalterservicelandingpage.service_4_description_en', 'Professional recording and processing of damage cases – from initial assessment to complete insurance settlement. We coordinate professionals, monitor deadlines and ensure complete documentation so claims are handled efficiently and correctly.');
        $this->migrator->add('translatable_verwalterservicelandingpage.service_5_title_de', 'Sanierungsbegleitung');
        $this->migrator->add('translatable_verwalterservicelandingpage.service_5_title_en', 'Renovation Support');
        $this->migrator->add('translatable_verwalterservicelandingpage.service_5_description_de', 'Strukturierte Begleitung von Instandhaltungs- und Sanierungsprojekten – von der Ausschreibung über die Angebotsprüfung bis zur Bauüberwachung. Wir behalten Kosten, Qualität und Zeitplan im Blick und stellen sicher, dass Maßnahmen wirtschaftlich und fachgerecht umgesetzt werden.');
        $this->migrator->add('translatable_verwalterservicelandingpage.service_5_description_en', 'Structured support for maintenance and renovation projects – from tender to bid review to construction supervision. We keep track of costs, quality and schedule and ensure measures are implemented economically and professionally.');
        $this->migrator->add('translatable_verwalterservicelandingpage.service_6_title_de', 'Energieausweise');
        $this->migrator->add('translatable_verwalterservicelandingpage.service_6_title_en', 'Energy Certificates');
        $this->migrator->add('translatable_verwalterservicelandingpage.service_6_description_de', 'Erstellung und Aktualisierung von Energieausweisen gemäß gesetzlicher Vorgaben. Wir koordinieren die technische Aufnahme, sorgen für eine normgerechte Berechnung und stellen die fristgerechte Bereitstellung bei Vermietung, Verkauf oder Sanierung sicher.');
        $this->migrator->add('translatable_verwalterservicelandingpage.service_6_description_en', 'Creation and updating of energy certificates according to legal requirements. We coordinate technical assessment, ensure standard-compliant calculation and guarantee timely provision for rental, sale or renovation.');
        $this->migrator->add('translatable_verwalterservicelandingpage.section_2_cta_text_de', 'Sie benötigen eine maßgeschneiderte Lösung? Wir entwickeln die optimale, individuelle Lösungen für Ihre Verwaltung.');
        $this->migrator->add('translatable_verwalterservicelandingpage.section_2_cta_text_en', 'Do you need a customized solution? We develop the optimal, individual solutions for your management.');
        $this->migrator->add('translatable_verwalterservicelandingpage.section_2_cta_button_de', 'Kontaktieren Sie uns');
        $this->migrator->add('translatable_verwalterservicelandingpage.section_2_cta_button_en', 'Contact Us');
        $this->migrator->add('translatable_verwalterservicelandingpage.section_3_tag_de', 'be trusted');
        $this->migrator->add('translatable_verwalterservicelandingpage.section_3_tag_en', 'be trusted');
        $this->migrator->add('translatable_verwalterservicelandingpage.section_3_headline_de', 'Schnelle, zuverlässige Umsetzung mit Qualitätsgarantie');
        $this->migrator->add('translatable_verwalterservicelandingpage.section_3_headline_en', 'Fast, reliable implementation with quality guarantee');
        $this->migrator->add('translatable_verwalterservicelandingpage.section_3_text_de', 'Ihre Verwaltung wird immer ins rechte Licht gerückt! Ob regelmäßige Objektkontrolle oder akuter Handlungsbedarf – wir reagieren rasch und handeln professionell. Ihre Reputation bei Eigentümern und Mietern ist auch unsere Verantwortung.');
        $this->migrator->add('translatable_verwalterservicelandingpage.section_3_text_en', 'Your management will always be put in the right light! Whether regular property inspection or urgent action needs – we respond quickly and act professionally. Your reputation with owners and tenants is also our responsibility.');
        $this->migrator->add('translatable_verwalterservicelandingpage.trust_1_title_de', 'Hohe Serviceorientierung');
        $this->migrator->add('translatable_verwalterservicelandingpage.trust_1_title_en', 'High Service Orientation');
        $this->migrator->add('translatable_verwalterservicelandingpage.trust_1_text_de', 'Wir arbeiten so lange, bis alle Beteiligten zufrieden sind.');
        $this->migrator->add('translatable_verwalterservicelandingpage.trust_1_text_en', 'We work until all parties are satisfied.');
        $this->migrator->add('translatable_verwalterservicelandingpage.trust_2_title_de', 'Transparente Erstberatung');
        $this->migrator->add('translatable_verwalterservicelandingpage.trust_2_title_en', 'Transparent Initial Consultation');
        $this->migrator->add('translatable_verwalterservicelandingpage.trust_2_text_de', 'Klare Einschätzung Ihrer Anforderungen – ohne versteckte Kosten.');
        $this->migrator->add('translatable_verwalterservicelandingpage.trust_2_text_en', 'Clear assessment of your requirements – without hidden costs.');
        $this->migrator->add('translatable_verwalterservicelandingpage.trust_3_title_de', 'Lokale Marktkenntnis');
        $this->migrator->add('translatable_verwalterservicelandingpage.trust_3_title_en', 'Local Market Knowledge');
        $this->migrator->add('translatable_verwalterservicelandingpage.trust_3_text_de', 'Wir kennen die Besonderheiten des Wiener Immobilienmarktes.');
        $this->migrator->add('translatable_verwalterservicelandingpage.trust_3_text_en', 'We know the specifics of the Vienna real estate market.');
        $this->migrator->add('translatable_verwalterservicelandingpage.trust_4_title_de', 'Schnelle Reaktionszeiten');
        $this->migrator->add('translatable_verwalterservicelandingpage.trust_4_title_en', 'Fast Response Times');
        $this->migrator->add('translatable_verwalterservicelandingpage.trust_4_text_de', 'Dringende Anliegen behandeln wir priorisiert.');
        $this->migrator->add('translatable_verwalterservicelandingpage.trust_4_text_en', 'We treat urgent matters as priority.');
        $this->migrator->add('translatable_verwalterservicelandingpage.trust_5_title_de', 'Flexible Terminvereinbarung');
        $this->migrator->add('translatable_verwalterservicelandingpage.trust_5_title_en', 'Flexible Appointment Scheduling');
        $this->migrator->add('translatable_verwalterservicelandingpage.trust_5_text_de', 'Auch außerhalb klassischer Bürozeiten.');
        $this->migrator->add('translatable_verwalterservicelandingpage.trust_5_text_en', 'Also outside of traditional office hours.');
        $this->migrator->add('translatable_verwalterservicelandingpage.trust_6_title_de', '100 % Transparenz');
        $this->migrator->add('translatable_verwalterservicelandingpage.trust_6_title_en', '100% Transparency');
        $this->migrator->add('translatable_verwalterservicelandingpage.trust_6_text_de', 'Nachvollziehbare Abläufe und strukturierte Dokumentation.');
        $this->migrator->add('translatable_verwalterservicelandingpage.trust_6_text_en', 'Traceable processes and structured documentation.');
        $this->migrator->add('translatable_verwalterservicelandingpage.section_4_tag_de', 'be easy');
        $this->migrator->add('translatable_verwalterservicelandingpage.section_4_tag_en', 'be easy');
        $this->migrator->add('translatable_verwalterservicelandingpage.section_4_headline_de', 'So funktioniert die Zusammenarbeit');
        $this->migrator->add('translatable_verwalterservicelandingpage.section_4_headline_en', 'How the collaboration works');
        $this->migrator->add('translatable_verwalterservicelandingpage.section_4_stat_number', '500+');
        $this->migrator->add('translatable_verwalterservicelandingpage.section_4_stat_text_de', 'betreute Objekte');
        $this->migrator->add('translatable_verwalterservicelandingpage.section_4_stat_text_en', 'managed properties');
        $this->migrator->add('translatable_verwalterservicelandingpage.step_1_title_de', 'Kontaktaufnahme');
        $this->migrator->add('translatable_verwalterservicelandingpage.step_1_title_en', 'Contact');
        $this->migrator->add('translatable_verwalterservicelandingpage.step_1_text_de', 'Sie schildern uns Ihren Bedarf telefonisch oder per E-Mail. Wir analysieren gemeinsam Ihre aktuelle Situation.');
        $this->migrator->add('translatable_verwalterservicelandingpage.step_1_text_en', 'You describe your needs by phone or email. We analyze your current situation together.');
        $this->migrator->add('translatable_verwalterservicelandingpage.step_2_title_de', 'Analyse & Angebot');
        $this->migrator->add('translatable_verwalterservicelandingpage.step_2_title_en', 'Analysis & Offer');
        $this->migrator->add('translatable_verwalterservicelandingpage.step_2_text_de', 'Wir definieren Leistungsumfang, Reaktionszeiten und Reporting-Struktur und erstellen ein transparentes Angebot.');
        $this->migrator->add('translatable_verwalterservicelandingpage.step_2_text_en', 'We define scope of services, response times and reporting structure and create a transparent offer.');
        $this->migrator->add('translatable_verwalterservicelandingpage.step_3_title_de', 'Umsetzung & Betreuung');
        $this->migrator->add('translatable_verwalterservicelandingpage.step_3_title_en', 'Implementation & Support');
        $this->migrator->add('translatable_verwalterservicelandingpage.step_3_text_de', 'Unser Team übernimmt die vereinbarten Leistungen – strukturiert, dokumentiert und zuverlässig. Sie erhalten regelmäßige Updates und volle Transparenz.');
        $this->migrator->add('translatable_verwalterservicelandingpage.step_3_text_en', 'Our team takes over the agreed services – structured, documented and reliable. You receive regular updates and full transparency.');
        $this->migrator->add('translatable_verwalterservicelandingpage.cta_tag_de', 'be relaxed');
        $this->migrator->add('translatable_verwalterservicelandingpage.cta_tag_en', 'be relaxed');
        $this->migrator->add('translatable_verwalterservicelandingpage.cta_headline_de', 'Bereit für professionelle Unterstützung?');
        $this->migrator->add('translatable_verwalterservicelandingpage.cta_headline_en', 'Ready for professional support?');
        $this->migrator->add('translatable_verwalterservicelandingpage.cta_text_de', 'Überzeugen Sie sich selbst von unserem Service für Verwalter! Gerne besprechen wir in einem unverbindlichen Erstgespräch, wie wir Ihre Hausverwaltung effizient entlasten können. Wir sind Ihr verlässlicher Partner in Wien und Österreich, wenn es um professionelle Unterstützung in der Immobilienverwaltung geht.');
        $this->migrator->add('translatable_verwalterservicelandingpage.cta_text_en', 'See for yourself our service for managers! We are happy to discuss in a non-binding initial meeting how we can efficiently relieve your property management. We are your reliable partner in Vienna and Austria when it comes to professional support in property management.');
        $this->migrator->add('translatable_verwalterservicelandingpage.cta_button_de', 'Jetzt Kontakt aufnehmen');
        $this->migrator->add('translatable_verwalterservicelandingpage.cta_button_en', 'Contact Us Now');
    }
};
