<?php

use Spatie\LaravelSettings\Migrations\SettingsMigration;

return new class extends SettingsMigration
{
public function up(): void
{
        $this->migrator->add('translatable_verwalterservice_landingpage.hero_tagline_de', 'professionell • individuell • effizient');
        $this->migrator->add('translatable_verwalterservice_landingpage.hero_tagline_en', 'professional • individual • efficient');
        $this->migrator->add('translatable_verwalterservice_landingpage.hero_headline_de', 'Zufriedene Kunden, die sich gut betreut fühlen, sind Ihr Kapital.');
        $this->migrator->add('translatable_verwalterservice_landingpage.hero_headline_en', 'Satisfied customers who feel well taken care of are your capital.');
        $this->migrator->add('translatable_verwalterservice_landingpage.hero_email', 'verwalterservice@bereal-immobilien.at');
        $this->migrator->add('translatable_verwalterservice_landingpage.hero_phone', '+43 1 535 36 19');
        $this->migrator->add('translatable_verwalterservice_landingpage.hero_feature_1_de', 'Schnelle Hilfe');
        $this->migrator->add('translatable_verwalterservice_landingpage.hero_feature_1_en', 'Quick Help');
        $this->migrator->add('translatable_verwalterservice_landingpage.hero_feature_2_de', 'Umfangreiche Dokumentation');
        $this->migrator->add('translatable_verwalterservice_landingpage.hero_feature_2_en', 'Comprehensive Documentation');
        $this->migrator->add('translatable_verwalterservice_landingpage.hero_feature_3_de', 'White-Label Service');
        $this->migrator->add('translatable_verwalterservice_landingpage.hero_feature_3_en', 'White-Label Service');
        $this->migrator->add('translatable_verwalterservice_landingpage.section_1_tag_de', 'serviced');
        $this->migrator->add('translatable_verwalterservice_landingpage.section_1_tag_en', 'serviced');
        $this->migrator->add('translatable_verwalterservice_landingpage.section_1_headline_de', 'Professionell für Ihre Hausverwaltung');
        $this->migrator->add('translatable_verwalterservice_landingpage.section_1_headline_en', 'Professional for Your Property Management');
        $this->migrator->add('translatable_verwalterservice_landingpage.section_1_text_de', 'Sie möchten sich auf Ihr Kerngeschäft konzentrieren und trotzdem erstklassigen Service bieten? Wir unterstützen Hausverwaltungen mit maßgeschneiderten Dienstleistungen, die Ihre Kunden begeistern und Ihren Arbeitsalltag entlasten.');
        $this->migrator->add('translatable_verwalterservice_landingpage.section_1_text_en', 'You want to focus on your core business and still offer first-class service? We support property management companies with customized services that delight your customers and relieve your daily workload.');
        $this->migrator->add('translatable_verwalterservice_landingpage.section_1_feature_1_de', 'Objektbegehungen');
        $this->migrator->add('translatable_verwalterservice_landingpage.section_1_feature_1_en', 'Property Inspections');
        $this->migrator->add('translatable_verwalterservice_landingpage.section_1_feature_2_de', 'Schadensdokumentation');
        $this->migrator->add('translatable_verwalterservice_landingpage.section_1_feature_2_en', 'Damage Documentation');
        $this->migrator->add('translatable_verwalterservice_landingpage.section_1_feature_3_de', 'Mieterbetreuung');
        $this->migrator->add('translatable_verwalterservice_landingpage.section_1_feature_3_en', 'Tenant Support');
        $this->migrator->add('translatable_verwalterservice_landingpage.section_1_feature_4_de', 'Kosteneffizient');
        $this->migrator->add('translatable_verwalterservice_landingpage.section_1_feature_4_en', 'Cost-Efficient');
        $this->migrator->add('translatable_verwalterservice_landingpage.section_1_feature_5_de', 'Versicherungsabwicklung');
        $this->migrator->add('translatable_verwalterservice_landingpage.section_1_feature_5_en', 'Insurance Processing');
        $this->migrator->add('translatable_verwalterservice_landingpage.section_1_feature_6_de', 'Nachhaltige Lösungen');
        $this->migrator->add('translatable_verwalterservice_landingpage.section_1_feature_6_en', 'Sustainable Solutions');
        $this->migrator->add('translatable_verwalterservice_landingpage.section_1_cta_de', 'Jetzt Beratung anfordern');
        $this->migrator->add('translatable_verwalterservice_landingpage.section_1_cta_en', 'Request Consultation Now');
        $this->migrator->add('translatable_verwalterservice_landingpage.section_2_tag_de', 'cared');
        $this->migrator->add('translatable_verwalterservice_landingpage.section_2_tag_en', 'cared');
        $this->migrator->add('translatable_verwalterservice_landingpage.section_2_headline_de', '360° Leistungen in der Immobilien Verwaltung');
        $this->migrator->add('translatable_verwalterservice_landingpage.section_2_headline_en', '360° Services in Property Management');
        $this->migrator->add('translatable_verwalterservice_landingpage.section_2_text_de', 'Von der Objektbegehung bis zur Sanierungsbegleitung – wir bieten Ihnen ein umfassendes Leistungspaket, das keine Wünsche offen lässt.');
        $this->migrator->add('translatable_verwalterservice_landingpage.section_2_text_en', 'From property inspections to renovation support – we offer you a comprehensive service package that leaves nothing to be desired.');
        $this->migrator->add('translatable_verwalterservice_landingpage.service_1_title_de', 'Objektbegehungen');
        $this->migrator->add('translatable_verwalterservice_landingpage.service_1_title_en', 'Property Inspections');
        $this->migrator->add('translatable_verwalterservice_landingpage.service_1_description_de', 'Regelmäßige Begehungen und Zustandsberichte Ihrer Liegenschaften. Wir dokumentieren den baulichen Zustand und identifizieren Handlungsbedarf frühzeitig.');
        $this->migrator->add('translatable_verwalterservice_landingpage.service_1_description_en', 'Regular inspections and condition reports of your properties. We document the structural condition and identify action needs early.');
        $this->migrator->add('translatable_verwalterservice_landingpage.service_2_title_de', 'Schadensmeldungen');
        $this->migrator->add('translatable_verwalterservice_landingpage.service_2_title_en', 'Damage Reports');
        $this->migrator->add('translatable_verwalterservice_landingpage.service_2_description_de', 'Professionelle Erfassung und Abwicklung von Schadensfällen. Lückenlose Dokumentation mit Fotos und detaillierten Berichten für Ihre Unterlagen.');
        $this->migrator->add('translatable_verwalterservice_landingpage.service_2_description_en', 'Professional recording and handling of damage cases. Complete documentation with photos and detailed reports for your records.');
        $this->migrator->add('translatable_verwalterservice_landingpage.service_3_title_de', 'Mieterkommunikation');
        $this->migrator->add('translatable_verwalterservice_landingpage.service_3_title_en', 'Tenant Communication');
        $this->migrator->add('translatable_verwalterservice_landingpage.service_3_description_de', 'Wir übernehmen die Kommunikation mit Ihren Mietern – von der Terminvereinbarung bis zur Beschwerdebearbeitung, stets freundlich und lösungsorientiert.');
        $this->migrator->add('translatable_verwalterservice_landingpage.service_3_description_en', 'We handle communication with your tenants – from scheduling appointments to handling complaints, always friendly and solution-oriented.');
        $this->migrator->add('translatable_verwalterservice_landingpage.service_4_title_de', 'Dokumentation & Reporting');
        $this->migrator->add('translatable_verwalterservice_landingpage.service_4_title_en', 'Documentation & Reporting');
        $this->migrator->add('translatable_verwalterservice_landingpage.service_4_description_de', 'Umfangreiche Dokumentation aller Vorgänge mit regelmäßigen Reports. Transparente Berichterstattung, damit Sie stets den Überblick behalten.');
        $this->migrator->add('translatable_verwalterservice_landingpage.service_4_description_en', 'Comprehensive documentation of all processes with regular reports. Transparent reporting so you always stay informed.');
        $this->migrator->add('translatable_verwalterservice_landingpage.service_5_title_de', 'Versicherungsabwicklung');
        $this->migrator->add('translatable_verwalterservice_landingpage.service_5_title_en', 'Insurance Processing');
        $this->migrator->add('translatable_verwalterservice_landingpage.service_5_description_de', 'Komplette Abwicklung von Versicherungsfällen – von der Schadensmeldung bis zur Regulierung. Wir koordinieren alle Beteiligten für Sie.');
        $this->migrator->add('translatable_verwalterservice_landingpage.service_5_description_en', 'Complete handling of insurance cases – from damage report to settlement. We coordinate all parties involved for you.');
        $this->migrator->add('translatable_verwalterservice_landingpage.service_6_title_de', 'Sanierungsbegleitung');
        $this->migrator->add('translatable_verwalterservice_landingpage.service_6_title_en', 'Renovation Support');
        $this->migrator->add('translatable_verwalterservice_landingpage.service_6_description_de', 'Professionelle Begleitung von Sanierungsprojekten – von der Planung bis zur Abnahme. Wir sorgen für reibungslose Abläufe und Qualitätskontrolle.');
        $this->migrator->add('translatable_verwalterservice_landingpage.service_6_description_en', 'Professional support for renovation projects – from planning to completion. We ensure smooth processes and quality control.');
        $this->migrator->add('translatable_verwalterservice_landingpage.section_2_cta_text_de', 'Sie benötigen eine maßgeschneiderte Lösung?');
        $this->migrator->add('translatable_verwalterservice_landingpage.section_2_cta_text_en', 'Do you need a customized solution?');
        $this->migrator->add('translatable_verwalterservice_landingpage.section_2_cta_button_de', 'Kontaktieren Sie uns');
        $this->migrator->add('translatable_verwalterservice_landingpage.section_2_cta_button_en', 'Contact Us');
        $this->migrator->add('translatable_verwalterservice_landingpage.section_3_tag_de', 'trusted');
        $this->migrator->add('translatable_verwalterservice_landingpage.section_3_tag_en', 'trusted');
        $this->migrator->add('translatable_verwalterservice_landingpage.section_3_headline_de', 'Schnell, Zuverlässig und mit Zufriedenheitsgarantie');
        $this->migrator->add('translatable_verwalterservice_landingpage.section_3_headline_en', 'Fast, Reliable and with Satisfaction Guarantee');
        $this->migrator->add('translatable_verwalterservice_landingpage.section_3_text_de', 'Egal ob es sich um eine routinemäßige Objektbegehung oder einen dringenden Schadensfall handelt – unser Team steht bereit, um schnell und professionell zu handeln. Ihre Zufriedenheit und die Ihrer Kunden stehen für uns an erster Stelle.');
        $this->migrator->add('translatable_verwalterservice_landingpage.section_3_text_en', 'Whether it\'s a routine property inspection or an urgent damage case – our team is ready to act quickly and professionally. Your satisfaction and that of your customers are our top priority.');
        $this->migrator->add('translatable_verwalterservice_landingpage.trust_1_title_de', 'Zufriedenheitsgarantie');
        $this->migrator->add('translatable_verwalterservice_landingpage.trust_1_title_en', 'Satisfaction Guarantee');
        $this->migrator->add('translatable_verwalterservice_landingpage.trust_1_text_de', 'Wir arbeiten so lange, bis Sie und Ihre Kunden zufrieden sind. Qualität ist unser Versprechen.');
        $this->migrator->add('translatable_verwalterservice_landingpage.trust_1_text_en', 'We work until you and your customers are satisfied. Quality is our promise.');
        $this->migrator->add('translatable_verwalterservice_landingpage.trust_2_title_de', 'Kostenlose Erstberatung');
        $this->migrator->add('translatable_verwalterservice_landingpage.trust_2_title_en', 'Free Initial Consultation');
        $this->migrator->add('translatable_verwalterservice_landingpage.trust_2_text_de', 'Unverbindliche Erstberatung, um Ihre Anforderungen zu verstehen und die passende Lösung zu finden.');
        $this->migrator->add('translatable_verwalterservice_landingpage.trust_2_text_en', 'Non-binding initial consultation to understand your requirements and find the right solution.');
        $this->migrator->add('translatable_verwalterservice_landingpage.trust_3_title_de', 'Lokale Experten');
        $this->migrator->add('translatable_verwalterservice_landingpage.trust_3_title_en', 'Local Experts');
        $this->migrator->add('translatable_verwalterservice_landingpage.trust_3_text_de', 'Unser Team kennt den Wiener Immobilienmarkt und die lokalen Gegebenheiten aus erster Hand.');
        $this->migrator->add('translatable_verwalterservice_landingpage.trust_3_text_en', 'Our team knows the Vienna real estate market and local conditions first-hand.');
        $this->migrator->add('translatable_verwalterservice_landingpage.trust_4_title_de', 'Schnelle Reaktionszeiten');
        $this->migrator->add('translatable_verwalterservice_landingpage.trust_4_title_en', 'Fast Response Times');
        $this->migrator->add('translatable_verwalterservice_landingpage.trust_4_text_de', 'Dringende Anliegen werden priorisiert. Bei Notfällen sind wir kurzfristig vor Ort verfügbar.');
        $this->migrator->add('translatable_verwalterservice_landingpage.trust_4_text_en', 'Urgent matters are prioritized. In emergencies, we are available on-site at short notice.');
        $this->migrator->add('translatable_verwalterservice_landingpage.trust_5_title_de', 'Flexible Termine');
        $this->migrator->add('translatable_verwalterservice_landingpage.trust_5_title_en', 'Flexible Appointments');
        $this->migrator->add('translatable_verwalterservice_landingpage.trust_5_text_de', 'Terminvereinbarungen, die sich an Ihrem Zeitplan orientieren – auch abends und am Wochenende möglich.');
        $this->migrator->add('translatable_verwalterservice_landingpage.trust_5_text_en', 'Appointment scheduling that fits your schedule – also possible in the evenings and on weekends.');
        $this->migrator->add('translatable_verwalterservice_landingpage.trust_6_title_de', '100% Transparent');
        $this->migrator->add('translatable_verwalterservice_landingpage.trust_6_title_en', '100% Transparent');
        $this->migrator->add('translatable_verwalterservice_landingpage.trust_6_text_de', 'Keine versteckten Kosten. Sie erhalten detaillierte Aufstellungen aller durchgeführten Arbeiten.');
        $this->migrator->add('translatable_verwalterservice_landingpage.trust_6_text_en', 'No hidden costs. You receive detailed statements of all work performed.');
        $this->migrator->add('translatable_verwalterservice_landingpage.section_4_tag_de', 'easy');
        $this->migrator->add('translatable_verwalterservice_landingpage.section_4_tag_en', 'easy');
        $this->migrator->add('translatable_verwalterservice_landingpage.section_4_headline_de', 'So funktioniert unser Verwalterservice');
        $this->migrator->add('translatable_verwalterservice_landingpage.section_4_headline_en', 'How Our Management Service Works');
        $this->migrator->add('translatable_verwalterservice_landingpage.section_4_stat_number', '500+');
        $this->migrator->add('translatable_verwalterservice_landingpage.section_4_stat_text_de', 'betreute Objekte');
        $this->migrator->add('translatable_verwalterservice_landingpage.section_4_stat_text_en', 'managed properties');
        $this->migrator->add('translatable_verwalterservice_landingpage.step_1_title_de', 'Kontaktaufnahme');
        $this->migrator->add('translatable_verwalterservice_landingpage.step_1_title_en', 'Contact');
        $this->migrator->add('translatable_verwalterservice_landingpage.step_1_text_de', 'Sie kontaktieren uns per Telefon oder E-Mail und schildern Ihren Bedarf. Wir nehmen uns Zeit für Ihre Anliegen und beraten Sie umfassend.');
        $this->migrator->add('translatable_verwalterservice_landingpage.step_1_text_en', 'You contact us by phone or email and describe your needs. We take time for your concerns and provide comprehensive advice.');
        $this->migrator->add('translatable_verwalterservice_landingpage.step_2_title_de', 'Bedarfsanalyse & Angebot');
        $this->migrator->add('translatable_verwalterservice_landingpage.step_2_title_en', 'Needs Analysis & Offer');
        $this->migrator->add('translatable_verwalterservice_landingpage.step_2_text_de', 'Nach der Kontaktaufnahme analysieren unsere Experten Ihren individuellen Bedarf und erstellen ein maßgeschneidertes Angebot für Sie.');
        $this->migrator->add('translatable_verwalterservice_landingpage.step_2_text_en', 'After initial contact, our experts analyze your individual needs and create a customized offer for you.');
        $this->migrator->add('translatable_verwalterservice_landingpage.step_3_title_de', 'Professionelle Umsetzung');
        $this->migrator->add('translatable_verwalterservice_landingpage.step_3_title_en', 'Professional Implementation');
        $this->migrator->add('translatable_verwalterservice_landingpage.step_3_text_de', 'Unser geschultes Team setzt alle vereinbarten Leistungen zuverlässig um. Sie erhalten lückenlose Dokumentation und regelmäßige Updates.');
        $this->migrator->add('translatable_verwalterservice_landingpage.step_3_text_en', 'Our trained team reliably implements all agreed services. You receive complete documentation and regular updates.');
        $this->migrator->add('translatable_verwalterservice_landingpage.cta_tag_de', 'kontakt');
        $this->migrator->add('translatable_verwalterservice_landingpage.cta_tag_en', 'contact');
        $this->migrator->add('translatable_verwalterservice_landingpage.cta_headline_de', 'Bereit für erstklassigen Service?');
        $this->migrator->add('translatable_verwalterservice_landingpage.cta_headline_en', 'Ready for First-Class Service?');
        $this->migrator->add('translatable_verwalterservice_landingpage.cta_text_de', 'Überzeugen Sie sich selbst von unserem Verwalterservice. Kontaktieren Sie uns für eine unverbindliche Erstberatung und erfahren Sie, wie wir Ihre Hausverwaltung unterstützen können.');
        $this->migrator->add('translatable_verwalterservice_landingpage.cta_text_en', 'See for yourself our management service. Contact us for a non-binding initial consultation and learn how we can support your property management.');
        $this->migrator->add('translatable_verwalterservice_landingpage.cta_button_de', 'Jetzt Kontakt aufnehmen');
        $this->migrator->add('translatable_verwalterservice_landingpage.cta_button_en', 'Contact Us Now');
    }
};
