<?php

namespace App\Forms\Components;

use Closure;
use App\Models\Settings;
use Filament\Forms\Components\BaseFileUpload;
use Filament\Forms\Components\Field;
use Filament\Forms\Components\FileUpload;
use Filament\Forms\Components\SpatieMediaLibraryFileUpload;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Arr;
use League\Flysystem\UnableToCheckFileExistence;
use Livewire\Features\SupportFileUploads\TemporaryUploadedFile;
use Spatie\MediaLibrary\MediaCollections\FileAdder;
use Spatie\MediaLibrary\MediaCollections\Models\Media;

class SettingsUpload extends FileUpload
{

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->afterStateHydrated(function (SettingsUpload $component, string|array|null $state) {

            if (blank($state) || $state == 0) {
                $component->state([]);
                return;
            }

            $component->state(Arr::wrap($state));
        });

        $this->getUploadedFileUsing(static function (SettingsUpload $component, string $file): ?array {


            if (blank($component->getState())) {
                return null;
            }

            $media = Media::whereId(intval($file))->first();
            $url ??= $media?->getUrl();

            return [
                'name' => $media?->getAttributeValue('name') ?? $media?->getAttributeValue('file_name'),
                'size' => $media?->getAttributeValue('size'),
                'type' => $media?->getAttributeValue('mime_type'),
                'url'  => $url,
            ];
        });

        $this->dehydrated(false);

        $this->saveUploadedFileUsing(static function (SettingsUpload $component, TemporaryUploadedFile $file): ?string {


            try {
                if (!$file->exists()) {
                    return null;
                }
            } catch (UnableToCheckFileExistence $exception) {
                return null;
            }


            $name = $component->getName();
            $setting = Settings::whereName($name)->first();

            $media = $setting->addMedia($file)
                ->withResponsiveImages()
                ->toMediaCollection($name);

            $payload = json_decode($setting->payload);

            $payload = is_null($payload) ? [] : Arr::wrap( $payload );
            $payload[] = $media->id;

            $setting->update(['payload' => $payload]);

            return $media->id;
        });

        $this->reorderUploadedFilesUsing(function (SettingsUpload $component, $state) {
            $ids = array_values(array_values($state));
            Media::setNewOrder( $ids );
            $setting = Settings::whereName($component->getName())->first();
            $setting->update(['payload' => $ids ]);

            return $state;
        });

        $this->deleteUploadedFileUsing(function (array|string|null $state, $component) {
           SettingsUpload::clearSettingMedia($component->getName(), $state);
        });


    }


    public static function clearSettingMedia($name, $state): void
    {

        $setting = Settings::whereName($name)->first();

        $payload = Arr::flatten($state);

        foreach ($setting->getMedia($name) as $media) {
            if(!in_array($media->id, $payload)) {
                $media->delete();
            }
        }

        $setting->update(['payload' => $payload]);
    }
}
