<?php

namespace App\Forms\Components;

use Closure;
use App\Models\Settings;
use Filament\Forms\Components\BaseFileUpload;
use Filament\Forms\Components\Field;
use Filament\Forms\Components\FileUpload;
use Filament\Forms\Components\SpatieMediaLibraryFileUpload;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Arr;
use League\Flysystem\UnableToCheckFileExistence;
use Livewire\Features\SupportFileUploads\TemporaryUploadedFile;
use Spatie\MediaLibrary\MediaCollections\FileAdder;
use Spatie\MediaLibrary\MediaCollections\Models\Media;

class SettingsUpload extends FileUpload
{

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->afterStateHydrated(function (SettingsUpload $component, string|array|null $state) {
            $state = intval($state);


            if (blank($state) || $state == 0) {
                $component->state([]);
                return;
            }

            $component->state(Arr::wrap($state));
        });

        $this->getUploadedFileUsing(static function (SettingsUpload $component, string $file): ?array {

            if (blank($component->getState())) {
                return null;
            }

            $media = Media::whereId($file)->first();
            $url ??= $media?->getUrl();

            return [
                'name' => $media?->getAttributeValue('name') ?? $media?->getAttributeValue('file_name'),
                'size' => $media?->getAttributeValue('size'),
                'type' => $media?->getAttributeValue('mime_type'),
                'url'  => $url,
            ];
        });

        $this->dehydrated(false);

        $this->saveUploadedFileUsing(static function (SettingsUpload $component, TemporaryUploadedFile $file): ?string {


            try {
                if (!$file->exists()) {
                    return null;
                }
            } catch (UnableToCheckFileExistence $exception) {
                return null;
            }


            $name = $component->getName();
            $setting = Settings::whereName($name)->first();

            $this->clearSettingMedia($this);

            $media = $setting->addMedia($file)
                ->withResponsiveImages()
                ->toMediaCollection($name);

            $setting->update(['payload' => $media->id]);

            return $media->id;
        });


        $this->deleteUploadedFileUsing(function (array|string|null $state) {
            $this->clearSettingMedia($this);
        });


    }


    protected function clearSettingMedia(SettingsUpload $component): void
    {
        $name = $component->getName();
        $setting = Settings::whereName($name)->first();

        foreach ($setting->getMedia($name) as $media) {
            $media->delete();
        }

        $setting->update(['payload' => 0]);
    }
}
